model:
  num_node_types: 3
  num_edge_types: 2
  hidden_dim: 64
  embed_dim: 64
  output_dim: 1
  n_layers: 2
  n_heads: 4
  dropout: 0.0
  attention_dropout: 0.0
  activation_dropout: 0.0
  drop_path_rate: 0.0
  use_performer: false
  performer_nb_features: 64
  performer_generalized_attention: true
  layernorm_style: prenorm
  tokenizer_lap_dim: 8
  tokenizer_lap_dropout: 0.0
  tokenizer_n_layers: 2
  phyla_dim: 16
trainer:
  record: false
  epochs: 3000
  checkpoint_dir: /n/netscratch/mzitnik_lab/Lab/yektefaie/PhylaFlowCheckpoints/overfit_pure_model_search/lr-0_0025-9657d0ca7272
  phyla_checkpoint_path: checkpoints/chkpts/epoch%3D00-step%3D004000-treefam_avg_normrf%3D0.6721.ckpt
  lr: 0.0025
  steps_callback: 100
  val_callback_freq: 0
  limit_val_batches: 0
  velocity_loss_mode: plain
  velocity_loss_plain_weight: 1.0
  velocity_sign_eps: 0.001
  training_step_velocity_weight: 100
  training_step_autoregressive_weight: 0.2
  training_step_autoregressive_grad_ratio: 0.05
  velocity_dt_candidate_weight: 1.0
  velocity_dt_hit_weight: 1.0
  velocity_event_weight: 0.0
  training_sampling_start: 1000
  num_warmup_steps: 0
data:
  nexus_root: ./example_data/nexus/
  mrbayes_root: ./example_data/runs/
  batch_size: 16
  num_workers: 0
  pin_memory: false
  sanity_check: false
  random_sanity_check: true
  overfit_velocity_zero: false
