model:
  num_node_types: 3
  num_edge_types: 2
  hidden_dim: 256
  embed_dim: 256
  output_dim: 256
  n_layers: 6
  n_heads: 8
  dropout: 0.1
  attention_dropout: 0.1
  activation_dropout: 0.1
  drop_path_rate: 0.0
  use_performer: true
  performer_nb_features: 64
  performer_generalized_attention: true
  layernorm_style: prenorm
  tokenizer_lap_dim: 16
  tokenizer_lap_dropout: 0.2
  tokenizer_n_layers: 6
  phyla_dim: 256

trainer:
  record: False
  epochs: 10000
  val_callback_frequency: 10
  checkpoint_dir: /n/holylfs06/LABS/mzitnik_lab/Users/yektefaie/PhylaFlow/checkpoint_dir/


data:
  # nexus_root: /n/netscratch/mzitnik_lab/Lab/yektefaie/phylaflow_datasets/nexus
  # mrbayes_root: /n/netscratch/mzitnik_lab/Lab/yektefaie/runs
  nexus_root: /Users/yashaektefaie/Desktop/PhylaFlow/example_data/nexus/
  mrbayes_root: /Users/yashaektefaie/Desktop/PhylaFlow/example_data/runs/
  batch_size: 16
  num_workers: 4
  pin_memory: False
