model:
  num_node_types: 3
  num_edge_types: 2
  hidden_dim: 256
  embed_dim: 256
  output_dim: 1
  n_layers: 6
  n_heads: 8
  dropout: 0.1
  attention_dropout: 0.1
  activation_dropout: 0.1
  drop_path_rate: 0.0
  use_performer: true
  performer_nb_features: 64
  performer_generalized_attention: true
  layernorm_style: prenorm
  tokenizer_lap_dim: 16
  tokenizer_lap_dropout: 0.2
  tokenizer_n_layers: 6
  phyla_dim: 256

trainer:
  record: False
  epochs: 2
  val_callback_freq: 0
  steps_callback: 100
  checkpoint_dir: ./checkpoints/
  lr: 0.0001


data:
  nexus_root: /home/leo/phyla/phylaflow_datasets/nexus/
  mrbayes_root: /home/leo/phyla/phylaflow_datasets/runs/
  batch_size: 4
  num_workers: 2
  pin_memory: False
